android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options="-Xmx1024m"
kotlin.code.style=official
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
# Fix for KAPT NonExistentClass error
kapt.use.incremental=false
kapt.use-k2=false
# 强制使用 wrapper
systemProp.https.protocols=TLSv1.2,TLSv1.3